cms/urls.py
from django.urls import path
from . import admin_views
import search.admin_views as search_views
from .models import Lab, Task, Assignment, Course, LabInCourse
from .admin_views import AssignmentFormMock, LabInCourseFormMock

app_name = 'cms'

# Custom admin for cms: Task, Lab, Course
urlpatterns = [
    # for downloading solution code
    path('admin/task/<int:task_id>/solution/', admin_views.get_sol, 
        name='admin-cms-task-get-sol'),
    
    # this is an ajax request from admin/cms/task/change_form.html
    path('admin/task/preview/', admin_views.preview_task,
        name='admin-cms-task-preview'),

    # for previewing task on an iframe
    path('admin/task/preview-iframe/', admin_views.preview_task_as_iframe,
        name='admin-cms-task-preview-iframe'),

    # for previewing cached child task on an iframe
    path('admin/cachedchildtask/preview-iframe/<int:parent_task_id>/<key>', admin_views.preview_childtask_as_iframe,
        name='admin-cms-childtask-preview-iframe'),

    # for creating new task version
    path('admin/task/<int:task_id>/new_version/', admin_views.new_task_version,
        name='admin-cms-task-new-version'),

    # for cloning task
    path('admin/task/<int:task_id>/clone/', admin_views.clone_task,
        name='admin-cms-task-clone'),

    # for testing task
    path('admin/task/<int:task_id>/test/', admin_views.test_task,
        name='admin-cms-task-test'),

    path('admin/task/help/', admin_views.task_syntax_help,
        name='admin-cms-task-help'),

    path('admin/lab/<int:lab_id>/clone/', admin_views.clone_lab,
        name='admin-cms-lab-clone'),

    path('admin/lab/<int:lab_id>/deepclone/', admin_views.deepclone_lab,
        name='admin-cms-lab-deep-clone'),
]

# Common search admin
urlpatterns += [
    #
    # These are for task selection in lab
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/lab/search/', 
        search_views.search_children, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment,
            'search_result_template': 
                'admin/cms/lab/include/task_search_result.html',
            'search_function': Task.search_by_tags
            },
        'admin-cms-lab-task-search'),
    
    # this is ajax called from add button
    path('admin/lab/addtask/', 
        search_views.add_child, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment, 
            'join_form_mock': AssignmentFormMock,
            'one_join_form_template': 
                'admin/cms/lab/include/assignment_inline_oneform.html'
            },
        'admin-cms-lab-add-task'),


    #
    # These are for lab selection in course
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/course/search/', 
        search_views.search_children, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse,
            'search_result_template': 
                'admin/cms/course/include/lab_search_result.html',
            'search_function': Lab.search_by_tags
            },
        'admin-cms-course-lab-search'),
    
    # this is ajax called from add button
    path('admin/course/addlab/', 
        search_views.add_child, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse, 
            'join_form_mock': LabInCourseFormMock,
            'one_join_form_template': 
                'admin/cms/course/include/labincourse_inline_oneform.html' 
            },
        'admin-cms-course-add-lab'),
]

elabsheet/urls.py
import os
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from lab.views import index

urlpatterns = [
    path('', index,name='index'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('cms/', include('cms.urls')),
    path('lab/', include('lab.urls')),
    path('instr/', include('instr.urls')),
    path('feedback/', include('feedback.urls')),
    path('taskpads/', include('taskpads.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.MATHJAX_ROOT_URL, document_root=settings.MATHJAX_ROOT_DIR)

instr/urls.py
from django.urls import path
from . import views

app_name = 'instr'

urlpatterns = [
    path('<int:sec_id>/',
        views.section_menu,
        name='section-menu'),
    path('assignments/<int:sec_id>/',
        views.list_assignments,
        name='list-assignments'),
    path('view/<int:sec_id>/<int:assign_id>/',
        views.view_submissions,
        name='view-submissions'),
    path('submissions/<int:sec_id>/<int:student_id>/<int:assign_id>',
        views.view_assignment_submissions,
        name='view-assignment-submissions'),
    path('regrade/<int:sec_id>/<int:submission_id>/',
        views.regrade_submission,
        name='regrade-submission'),
    path('delete/<int:sec_id>/<int:submission_id>/',
        views.delete_submission,
        name='delete-submission'),
    path('regradeall/<int:sec_id>/<int:assign_id>/',
        views.regrade_submissions,
        name='regrade-submissions'),
    path('zip/<int:sec_id>/code<int:assign_id>.zip',
        views.zip_submissions,
        name='zip-submissions'),
    path('zip/<int:sec_id>/text<int:assign_id>.zip',
        views.zip_text_submissions,
        name='zip-text-submissions'),
    path('gradebook/<int:sec_id>/',
        views.gradebook,
        name='gradebook'),
    path('gradebook/csv/<int:sec_id>/',
        views.gradebook_csv,
        name='gradebook-csv'),
    path('labs/<int:sec_id>/',
        views.list_labs,
        name='list-labs'),
    path('lab/<int:labinsec_id>/report/',
        views.report_lab_status,
        name='lab-status-report'),
    path('labs/<int:sec_id>/options',
        views.show_lab_options,
        name='lab-options'),
    path('lab/<int:labinsec_id>/acl',
        views.edit_acl,
        name='edit-acl'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts',
        views.manage_direct_accounts,
        name='manage-direct-accounts'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/remove/<int:user_id>',
        views.remove_direct_account,
        name='remove-direct-account'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/generate/<int:user_id>',
        views.generate_direct_account,
        name='generate-direct-account'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/action',
        views.direct_accounts_action,
        name='direct-accounts-action'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/export',
        views.export_direct_accounts,
        name='export-direct-accounts'),
    path('logs/<int:sec_id>',
        views.report_section_log,
        name='log-report'),

    # ajax request
    path('grade/<int:submission_id>/',
        views.grade_submission,
        name='grade-submission'),
    path('lab/status/<int:lab_id>/',
        views.lab_status,
        name='lab-status'),
]

instr/views.py
from zipfile import ZipFile, ZipInfo, ZIP_DEFLATED
from datetime import datetime,timedelta
import json

from django import template
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseForbidden, \
        HttpResponseRedirect, JsonResponse
from django.urls import reverse

from commons.decorators import instructor_required, ajax_login_required
from commons.utils import find_extension
from django.contrib.auth.models import User
from lab.models import Section, Submission, Assignment, LabInSection, \
        AddressAcl, DirectToLabAccount
from lab.views import get_section_statistic_for_user
from logger.models import Log

import codecs

@login_required
@instructor_required
def section_menu(request,sec_id):
    '''Displays the main menu for a section in the instructor's view.'''
    sec = get_object_or_404(Section, pk=sec_id)
    inqueue_count = Submission.count_inqueue_submissions()
    return render(request, 'instr/section_menu.html', 
            {
                'sec' : sec,
                'inqueue_count': inqueue_count,
            })


@login_required
@instructor_required
def list_assignments(request,sec_id):
    '''Lists all assignments in the chosen section.'''
    sec = get_object_or_404(Section, pk=sec_id)
    return render(request, 'instr/assignments.html', { 'sec' : sec })


@login_required
@instructor_required
def show_lab_options(request,sec_id):
    '''Displays menu for settings lab options'''
    sec = get_object_or_404(Section, pk=sec_id)
    return render(request, 'instr/lab-options.html', { 'sec' : sec })


@login_required
@instructor_required
def manage_direct_accounts(request,sec_id,labinsec_id):
    '''Displays page for managing direct-to-lab accounts'''
    labinsec = get_object_or_404(LabInSection, pk=labinsec_id)

    # XXX should we try using ORM below?
    students = User.objects.raw('''
        SELECT 
          user.id AS id,
          user.username AS username,
          filtered_da.id AS direct_id,
          filtered_da.username AS direct_user,
          filtered_da.password AS direct_passwd,
          filtered_da.enabled AS enabled
        FROM
          auth_user AS user
        INNER JOIN lab_section_students AS sec
          ON (user.id = sec.user_id AND sec.section_id = %s)
        LEFT JOIN (
          SELECT * FROM lab_directtolabaccount AS da WHERE da.labinsec_id = %s
        ) AS filtered_da
          ON (user.id = filtered_da.user_id)
        ORDER BY
          user.username
    ''',[labinsec.section_id,labinsec.id])
    
    return render(request, 'instr/direct-accounts.html', {
        'labinsec' : labinsec,
        'sec' : labinsec.section,
        'students' : students,
        })



@login_required
@instructor_required
def remove_direct_account(request,sec_id,labinsec_id,user_id):
    da = get_object_or_404(DirectToLabAccount,user__id=user_id,labinsec__id=labinsec_id)
    da.delete()
    return redirect('instr:manage-direct-accounts',sec_id,labinsec_id)


@login_required
@instructor_required
def direct_accounts_action(request,sec_id,labinsec_id):
    if request.method == 'POST':
        labinsec = get_object_or_404(LabInSection,id=labinsec_id)
        user_ids = [int(x) for x in request.POST.getlist('da')]
        if request.POST['action'] == 'generate':
            for uid in user_ids:
                try:
                    user = User.objects.get(id=uid)
                except User.DoesNotExist:
                    continue
                DirectToLabAccount.generate(user,labinsec)
        elif request.POST['action'] == 'remove':
            DirectToLabAccount.objects.filter(
                    labinsec=labinsec,user_id__in=user_ids).delete()
        elif request.POST['action'] == 'enable':
            DirectToLabAccount.objects.filter(
                    labinsec=labinsec,user_id__in=user_ids).update(enabled=True)
        elif request.POST['action'] == 'disable':
            DirectToLabAccount.objects.filter(
                    labinsec=labinsec,user_id__in=user_ids).update(enabled=False)
    return redirect('instr:manage-direct-accounts',sec_id,labinsec_id)


@login_required
@instructor_required
def generate_direct_account(request,sec_id,labinsec_id,user_id):
    labinsec = get_object_or_404(LabInSection,id=labinsec_id)
    user = get_object_or_404(User,id=user_id)
    DirectToLabAccount.generate(user,labinsec)
    return redirect('instr:manage-direct-accounts',sec_id,labinsec_id)


@login_required
@instructor_required
def generate_all_direct_accounts(request,sec_id,labinsec_id):
    labinsec = get_object_or_404(LabInSection, pk=labinsec_id)
    for student in labinsec.section.students.all():
        DirectToLabAccount.generate(student,labinsec)
    return redirect('instr:manage-direct-accounts',sec_id,labinsec_id)


@login_required
@instructor_required
def remove_all_direct_accounts(request,sec_id,labinsec_id):
    labinsec = get_object_or_404(LabInSection, pk=labinsec_id)
    DirectToLabAccount.objects.filter(labinsec=labinsec).delete()
    return redirect('instr:manage-direct-accounts',sec_id,labinsec_id)


@login_required
@instructor_required
def export_direct_accounts(request,sec_id,labinsec_id):
    labinsec = get_object_or_404(LabInSection, pk=labinsec_id)
    da_list = DirectToLabAccount.objects.filter(labinsec=labinsec).order_by('user')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = \
            'attachment; filename=direct-accounts-{}.csv'.format(labinsec.id)
    response.write('username,name,direct-account,password,enabled\n')
    for da in da_list:
        response.write('{},{} {},{},{},{}\n'.format(
            da.user.username,
            da.user.first_name,
            da.user.last_name,
            da.username,
            da.password,
            'yes' if da.enabled else 'no',
        ))
    return response


@login_required
@instructor_required
def view_submissions(request,sec_id,assign_id):
    '''Shows all students' submissions with a score box attached to each
    text-based blank.  A submission can be graded and saved.'''
    assignment = get_object_or_404(Assignment, pk=assign_id)
    task = assignment.task
    sec = get_object_or_404(Section, pk=sec_id)
    recent_submissions = [(std, assignment.get_recent_submission_for_user(std,sec))
            for std in sec.students.all()]
    json_scores = json.dumps({std.username:submission.manual_scores
        for (std,submission) in recent_submissions if submission})
    submission_list = [(std, submission)
            for (std,submission) in recent_submissions if submission]

    # sort the submission list by submission time
    submission_list.sort(
            key=lambda std_sub_scr: std_sub_scr[1].submitted_at,
            reverse=True)

    return render(request, 'instr/submissions.html', 
            { 
                'sec' : sec,
                'submissions' : submission_list,
                'assignment' : assignment,
                'task' : task,
                'json_scores' : json_scores,
            })


@login_required
@instructor_required
def regrade_submission(request,sec_id,submission_id):
    '''Triggers regrading of specified submission'''
    previous_url = request.GET['next']
    submission = get_object_or_404(Submission,pk=submission_id)
    submission.code_grading_status = Submission.CODE_STATUS_INQUEUE
    submission.save()
    return HttpResponseRedirect(previous_url)

@login_required
@instructor_required
def delete_submission(request,sec_id,submission_id):
    previous_url = request.GET['next']
    submission = get_object_or_404(Submission,pk=submission_id)
    submission.delete()
    return HttpResponseRedirect(previous_url)


@login_required
@instructor_required
def regrade_submissions(request,sec_id,assign_id):
    '''Triggers all recent submissions for this assignment to be
    regraded.'''
    assignment = get_object_or_404(Assignment, pk=assign_id)
    sec = get_object_or_404(Section, pk=sec_id)
    recent_submissions = [(std, assignment.get_recent_submission_for_user(std,sec))
            for std in sec.students.all()]
    for std, submission in recent_submissions:
        if submission!=None:
            submission.code_grading_status = Submission.CODE_STATUS_INQUEUE
            submission.save()
    return redirect("instr:list-assignments",sec_id)


@login_required
@instructor_required
def zip_submissions(request,sec_id,assign_id):
    '''Returns all student submitted source files from the given assignment in
    form of a zip file'''
    assignment = get_object_or_404(Assignment, pk=assign_id)
    task = assignment.task
    sec = get_object_or_404(Section, pk=sec_id)
    recent_submissions = [(std, assignment.get_recent_submission_for_user(std,sec))
            for std in sec.students.all()]
    submissions = filter(lambda std_sub:std_sub[1] is not None, recent_submissions)
    response = HttpResponse(content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename=code%s.zip' % assign_id
    zip = ZipFile(response, mode='w', compression=ZIP_DEFLATED)
    ext = find_extension(task.language)
    for std,submission in submissions:
        fname = '%s/a%s.%s' % (std.username, assign_id, ext)
        submit_time = submission.submitted_at
        zip_info = ZipInfo(str(fname))
        zip_info.external_attr = 0o644 << 16
        zip_info.date_time = (
                submit_time.year,
                submit_time.month,
                submit_time.day,
                submit_time.hour, 
                submit_time.minute, 
                submit_time.second
                )
        zip.writestr(zip_info, 
                     codecs.encode(task.code.dump(submission.answer),
                                   'utf8'))
    response.close()
    return response


@login_required
@instructor_required
def zip_text_submissions(request,sec_id,assign_id):

templates/instr/assignment-submissions.html
{% extends "lab/base.html" %}
{% load static %}
{% load elab_conf %}
{% load elab_submission %}
{% load mathjax %}

{% block title %}View All Submissions for Assignment{% endblock %}

{% block top_title %}
{{ block.super }} | <a href="{% url 'instr:section-menu' sec.id %}">{{ sec }}</a>
{% endblock %}

{% block extra-head %}
  {{block.super}}
  {% mathjax %}
  <style type="text/css">
    div.submission
    {
        border: 1px solid gray;
        padding: 5px;
        margin-top: 5px;
        margin-bottom: 10px;
        display: none;
    }
    </style>
{% endblock %}

{% block content %}
<h1>View All Submissions for Student</h1>
<div style="margin:5px;">
  <b>Student:</b> {{student.first_name}} {{student.last_name}} ({{student.username}})<br/>
  <b>Assignment:</b> {{assignment.lab}} &rarr;
  <a href="{% url 'instr:view-submissions' sec.id assignment.id %}" target="_blank">{{assignment.task}}</a>
  <br/>
  <b>Number of submission(s):</b> {{submissions|length}}
  <button id="show-hide-all">Show All</button>
  <ul>
    {% for submission in submissions %}
    <li>
    <a href="#" class="submission">{{submission.submitted_at|date:"M d Y G:i:s"}}
      from {{submission.remote_addr}}</a>
        Result: {% sub_status_detailed submission %}
        <a class="btn btn-outline-info" 
          href="{% url 'instr:regrade-submission' sec.id submission.id %}?next={{request.path}}">regrade</a>
        <a class="btn btn-outline-danger" 
          onclick="return confirm('Do you want to delete this submission?');"
          href="{% url 'instr:delete-submission' sec.id submission.id %}?next={{request.path}}">delete</a>
        <div class="submission" id="submission-{{submission.id}}">
          {{submission.html}}
        </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

{% block footer %}
<script>
  var manual_scores = {{manual_scores_json|safe}};
  $(document).ready(function()
  {
    // toggle submission when the timestamp is clicked
    $("a.submission").click(function(event) 
    {
      event.preventDefault();
      $(this).nextAll("div.submission").slideToggle("normal");
    });

    $("#show-hide-all").click(function () {
      if ($(this).text() == "Show All") {
        $("div.submission").show();
        $(this).text("Hide All");
      }
      else {
        $("div.submission").hide();
        $(this).text("Show All");
      }
    });

    for (var s in manual_scores) {
      var submission_scores = manual_scores[s];
      var $element = $("div#submission-"+s);
      ElabClient.create_manual_score_boxes($element,{readOnly:true});
      ElabClient.update_manual_score_boxes($element,submission_scores);
    }

  });
</script>
{% endblock %}

templates/instr/assignments.html
{% extends "lab/base.html" %}
{% load static %}

{% block title %}Instructor Section Menu{% endblock %}

{% block top_title %}
{{ block.super }} | <a href="{% url 'instr:section-menu' sec.id %}">{{ sec }}</a>
{% endblock %}

{% block content %}
<h1>Assignment List</h1>
<ul>
    {% for labinsection in sec.labinsection_set.all %}
    <li><b>{{labinsection}}</b>
    <ul>
        {% for assignment in labinsection.lab.assignment_set.all %}
        <li>{{ assignment }}: <br/>
          <a class="btn btn-outline-info" href="{% url 'instr:view-submissions' sec.id assignment.id %}">view submissions and grade manual fields</a>
          <a class="btn btn-outline-info regrade-button" href="{% url 'instr:regrade-submissions' sec.id assignment.id %}?next={{request.path}}">regrade</a>
          <a class="btn btn-outline-info" href="{% url 'instr:zip-submissions' sec.id assignment.id %}">zipped code</a>
          <a class="btn btn-outline-info" href="{% url 'instr:zip-text-submissions' sec.id assignment.id %}">zipped text answers</a>
        </li>
        {% endfor %}
    </ul>
    </li>

    {% endfor %}
</ul>
<script>
$("a.regrade-button").click(function() {
  return confirm("This causes heavy load to the server. Are you sure?");
});
</script>
{% endblock %}

templates/instr/direct-accounts.html
{% extends "lab/base.html" %}

{% load elab_conf %}
{% load static %}

{% block extra-head %}
<script type="text/javascript" src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
<style>
  div .student-table {
    overflow-x: auto;
    padding: 5px;
  }

  table {
    border-collapse: collapse;
    border-spacing: 0;
    border: 1px solid #ddd;
  }

  th {
    text-align: center;
    padding: 8px;
  }

  td {
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even){ background-color: #f2f2f2; }
  tr.disabled { background-color: #ffcccc; !important }

  tr.entry:hover {
    background-color: #ffa;
  }
</style>

<script>
  $(function() {
    var $select_all = $("input#select-all");
    $select_all.change(function() {
      $("input[name='da']").prop("checked",$select_all.prop("checked"));
    });
  });
</script>

{% endblock %}

{% block title %}Lab Options{% endblock %}

{% block top_title %}
{{ block.super }} | <a href="{% url 'instr:section-menu' sec.id %}">{{ sec }}</a>
{% endblock %}

{% block content %}
<h1>Manage Direct-to-Lab Accounts</h1>
<div style="padding:5px">
  <b>Section:</b> {{sec}} <br/>
  <b>Lab:</b> {{labinsec.number}} - {{labinsec.lab}}
</div>
<form action="{% url 'instr:direct-accounts-action' sec.id labinsec.id %}" method="POST">
  {% csrf_token %}
  <div class="student-table">
    <table>
      <tr>
        <th><input type="checkbox" id="select-all"></th>
        <th>Username</th>
        <th>Direct-to-lab Account</th>
        <th>Password</th>
        <th>Enabled</th>
        <th>Action</th>
      </tr>
      {% for s in students %}
      <tr class="entry {{s.enabled|yesno:',disabled,'}}">
        <td><input type="checkbox" name="da" value="{{s.id}}"></td>
        <td>{{s.username}}</td>
        <td style="text-align:center; color:brown"><tt>{{s.direct_user|default:"-"}}</tt></td>
        <td style="text-align:center; color:brown"><tt>{{s.direct_passwd|default:"-"}}</tt></td>
        <td style="text-align:center">{{s.enabled|yesno:"yes,no,-"}}</td>
        <td>
          {% if s.direct_id %}
            <a href="{% url 'instr:generate-direct-account' sec.id labinsec.id s.id %}"
              class="btn btn-outline-success" onclick="return confirm('Account exists.  Continue?');">generate</a>
            <a href="{% url 'instr:remove-direct-account' sec.id labinsec.id s.id %}" 
              class="btn btn-outline-danger" onclick="return confirm('Are you sure?');">remove</a>
            <a href="{% url 'admin:lab_directtolabaccount_change' s.direct_id %}" 
              class="btn btn-outline-primary" target="_blank">edit</a>
          {% else %}
            <a href="{% url 'instr:generate-direct-account' sec.id labinsec.id s.id %}" class="btn btn-outline-success">generate</a>
            <a href="#" class="btn btn-outline-danger disabled">remove</a>
            <a href="{% url 'admin:lab_directtolabaccount_add' %}?user={{s.id}}&labinsec={{labinsec.id}}"
              class="btn btn-outline-primary" target="_blank">edit</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div style="padding:5px">
    <button class="btn btn-outline-success"
      name="action" value="generate"
      onclick="return confirm('This will replace selected accounts.  Continue?');">Generate Selected</button>
    <button class="btn btn-outline-danger"
      name="action" value="remove"
      onclick="return confirm('This will remove selected accounts.  Continue?');">Remove Selected</button>
    <button class="btn btn-outline-info"
      name="action" value="enable"
      onclick="return confirm('This will enable selected accounts.  Continue?');">Enable Selected</button>
    <button class="btn btn-outline-warning"
      name="action" value="disable"
      onclick="return confirm('This will disable selected accounts.  Continue?');">Disable Selected</button>
  </div>
  <div style="padding:5px">
    <a href="{% url 'instr:export-direct-accounts' sec.id labinsec.id %}"
      class="btn btn-outline-primary">Export CSV</a>
  </div>
</div>
{% endblock %}

templates/instr/section_menu.html
{% extends "lab/base.html" %}

{% load elab_conf %}
{% load static %}

{% block title %}Instructor Section Menu{% endblock %}

{% block top_title %}
{{ block.super }} | {{ sec }}
{% endblock %}

{% block content %}
<h1>Section Information</h1>
<ul>
  <li><a style="font-weight:bold" href="{% url 'admin:lab_section_change' sec.id %}">Manage section</a><br/>
  Change section name; enroll/unenroll students; add/delete labs; publish announcements
  </li>
  <li><a style="font-weight:bold" href="{% url 'instr:lab-options' sec.id %}">Change lab options</a><br/>
  View/modify each lab's settings such as task hiding and access control
  </li>
  <li><a style="font-weight:bold" href="{% url 'instr:list-assignments' sec.id %}">See all assignments</a><br/>
  View/grade student manual submissions; regrade students' code; download all codes in zip format
  </li>
  <li><a style="font-weight:bold" href="{% url 'instr:list-labs' sec.id %}">Lab Status</a><br/>
  View all student progress in each lab; download detailed CSV report for each lab
  </li>
  <li><a style="font-weight:bold" href="{% url 'instr:gradebook' sec.id %}">Student gradebook</a><br/>
  View/download all students' summarized scores
  </li>
  <li><a style="font-weight:bold" href="{% url 'instr:log-report' sec.id %}">Today's logs</a><br/>
  Returns all logs for this section, starting from yesterday. (Very computationally intensive, please try to use it once a day)
  </li>
</ul>

<b>Grader status</b>:
Current outstanding grading job{{ inqueue_count|pluralize }}: {{ inqueue_count }}

<hr/>
<h2>Instructor(s)</h2>
{% for i in sec.instructors.all %}
    {{i}}
{% endfor %}
<hr/>
<h2>Students</h2>
    <p>Number of enrolled students: {{ sec.students.count }}</p>
    <p>
    <table border="1" cellpadding="3" style="border: 1px solid #C3C3C3; border-collapse: collapse; margin: 5px;">
        {% for s in sec.students.all %}
        <tr><td>{{s.username}}</td><td>{{s.first_name}} {{s.last_name}}</td></tr>
        {% endfor %}
    </table>
    </p>

{% endblock %}
