cms/urls.py
from django.urls import path
from . import admin_views
import search.admin_views as search_views
from .models import Lab, Task, Assignment, Course, LabInCourse
from .admin_views import AssignmentFormMock, LabInCourseFormMock

app_name = 'cms'

# Custom admin for cms: Task, Lab, Course
urlpatterns = [
    # for downloading solution code
    path('admin/task/<int:task_id>/solution/', admin_views.get_sol, 
        name='admin-cms-task-get-sol'),
    
    # this is an ajax request from admin/cms/task/change_form.html
    path('admin/task/preview/', admin_views.preview_task,
        name='admin-cms-task-preview'),

    # for previewing task on an iframe
    path('admin/task/preview-iframe/', admin_views.preview_task_as_iframe,
        name='admin-cms-task-preview-iframe'),

    # for previewing cached child task on an iframe
    path('admin/cachedchildtask/preview-iframe/<int:parent_task_id>/<key>', admin_views.preview_childtask_as_iframe,
        name='admin-cms-childtask-preview-iframe'),

    # for creating new task version
    path('admin/task/<int:task_id>/new_version/', admin_views.new_task_version,
        name='admin-cms-task-new-version'),

    # for cloning task
    path('admin/task/<int:task_id>/clone/', admin_views.clone_task,
        name='admin-cms-task-clone'),

    # for testing task
    path('admin/task/<int:task_id>/test/', admin_views.test_task,
        name='admin-cms-task-test'),

    path('admin/task/help/', admin_views.task_syntax_help,
        name='admin-cms-task-help'),

    path('admin/lab/<int:lab_id>/clone/', admin_views.clone_lab,
        name='admin-cms-lab-clone'),

    path('admin/lab/<int:lab_id>/deepclone/', admin_views.deepclone_lab,
        name='admin-cms-lab-deep-clone'),
]

# Common search admin
urlpatterns += [
    #
    # These are for task selection in lab
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/lab/search/', 
        search_views.search_children, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment,
            'search_result_template': 
                'admin/cms/lab/include/task_search_result.html',
            'search_function': Task.search_by_tags
            },
        'admin-cms-lab-task-search'),
    
    # this is ajax called from add button
    path('admin/lab/addtask/', 
        search_views.add_child, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment, 
            'join_form_mock': AssignmentFormMock,
            'one_join_form_template': 
                'admin/cms/lab/include/assignment_inline_oneform.html'
            },
        'admin-cms-lab-add-task'),


    #
    # These are for lab selection in course
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/course/search/', 
        search_views.search_children, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse,
            'search_result_template': 
                'admin/cms/course/include/lab_search_result.html',
            'search_function': Lab.search_by_tags
            },
        'admin-cms-course-lab-search'),
    
    # this is ajax called from add button
    path('admin/course/addlab/', 
        search_views.add_child, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse, 
            'join_form_mock': LabInCourseFormMock,
            'one_join_form_template': 
                'admin/cms/course/include/labincourse_inline_oneform.html' 
            },
        'admin-cms-course-add-lab'),
]

elabsheet/urls.py
import os
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from lab.views import index

urlpatterns = [
    path('', index,name='index'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('cms/', include('cms.urls')),
    path('lab/', include('lab.urls')),
    path('instr/', include('instr.urls')),
    path('feedback/', include('feedback.urls')),
    path('taskpads/', include('taskpads.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.MATHJAX_ROOT_URL, document_root=settings.MATHJAX_ROOT_DIR)

instr/urls.py
from django.urls import path
from . import views

app_name = 'instr'

urlpatterns = [
    path('<int:sec_id>/',
        views.section_menu,
        name='section-menu'),
    path('assignments/<int:sec_id>/',
        views.list_assignments,
        name='list-assignments'),
    path('view/<int:sec_id>/<int:assign_id>/',
        views.view_submissions,
        name='view-submissions'),
    path('submissions/<int:sec_id>/<int:student_id>/<int:assign_id>',
        views.view_assignment_submissions,
        name='view-assignment-submissions'),
    path('regrade/<int:sec_id>/<int:submission_id>/',
        views.regrade_submission,
        name='regrade-submission'),
    path('delete/<int:sec_id>/<int:submission_id>/',
        views.delete_submission,
        name='delete-submission'),
    path('regradeall/<int:sec_id>/<int:assign_id>/',
        views.regrade_submissions,
        name='regrade-submissions'),
    path('zip/<int:sec_id>/code<int:assign_id>.zip',
        views.zip_submissions,
        name='zip-submissions'),
    path('zip/<int:sec_id>/text<int:assign_id>.zip',
        views.zip_text_submissions,
        name='zip-text-submissions'),
    path('gradebook/<int:sec_id>/',
        views.gradebook,
        name='gradebook'),
    path('gradebook/csv/<int:sec_id>/',
        views.gradebook_csv,
        name='gradebook-csv'),
    path('labs/<int:sec_id>/',
        views.list_labs,
        name='list-labs'),
    path('lab/<int:labinsec_id>/report/',
        views.report_lab_status,
        name='lab-status-report'),
    path('labs/<int:sec_id>/options',
        views.show_lab_options,
        name='lab-options'),
    path('lab/<int:labinsec_id>/acl',
        views.edit_acl,
        name='edit-acl'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts',
        views.manage_direct_accounts,
        name='manage-direct-accounts'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/remove/<int:user_id>',
        views.remove_direct_account,
        name='remove-direct-account'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/generate/<int:user_id>',
        views.generate_direct_account,
        name='generate-direct-account'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/action',
        views.direct_accounts_action,
        name='direct-accounts-action'),
    path('lab/<int:sec_id>/<int:labinsec_id>/direct-accounts/export',
        views.export_direct_accounts,
        name='export-direct-accounts'),
    path('logs/<int:sec_id>',
        views.report_section_log,
        name='log-report'),

    # ajax request
    path('grade/<int:submission_id>/',
        views.grade_submission,
        name='grade-submission'),
    path('lab/status/<int:lab_id>/',
        views.lab_status,
        name='lab-status'),
]

lab/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views,admin_views

app_name = 'lab'

urlpatterns = [
    path('<int:sec_id>/',
        views.list_labs,
        name='list-labs'),
    path('<int:sec_id>/<int:labinsec_id>/',
        views.show_lab,
        name='show-lab'),
    path('<int:sec_id>/<int:labinsec_id>/<int:cur_assignment_id>/',
        views.show_lab,
        name='show-assignment'),
    path('submit/<int:sec_id>/<int:labinsec_id>/<int:assignment_id>/',
        views.submit,
        name='submit-assignment'),

    # ajax request          
    path('assignment/<int:sec_id>/<int:labinsec_id>/<int:assignment_id>/', 
        views.get_assignment,
        name='get-assignment'),
    path('submissions/<int:sec_id>/<int:assignment_id>/',
        views.get_all_submissions,
        name='get-all-submissions'),
    path('submission/<int:sec_id>/<int:assignment_id>/<int:cur_submission_id>/',
        views.get_submission,
        name='get-submission'),
    path('submission/<int:submission_id>/copy/',
        views.copy_submission,
        name='copy-submission'),
    path('submission/<int:submission_id>/status/',
        views.get_submission_status,
        name='get-submission-status'),
    path('submission/<int:submission_id>/explain/',
        views.explain_submission_results,
        name='explain-submission-results'),
]

# Admin for lab: Section management
urlpatterns += [

    # enroll students
    path('admin/section/<int:section_id>/enrollment/', 
        admin_views.list_enroll_students,
        name='admin-lab-section-enrollment'),
    path('admin/section/<int:section_id>/enrollment/add', 
        admin_views.enroll_one_student,
        name='admin-lab-section-enrollment-add'),
    path('admin/section/<int:section_id>/enrollment/upload', 
        admin_views.upload_student_list,
        name='admin-lab-section-enrollment-upload'),
    path('admin/section/<int:section_id>/enrollment/delete', 
        admin_views.unenroll_students,
        name='admin-lab-section-unenroll'),

    # lab set
    path('admin/section/<int:section_id>/labs/',
        admin_views.list_labs_in_section,
        name='admin-lab-section-labs'),
    path('admin/section/<int:section_id>/labs/update',
        admin_views.update_labs_in_section,
        name='admin-lab-section-labs-update'),
    path('admin/section/<int:section_id>/labs/add',
        admin_views.add_labs_in_section,
        name='admin-lab-section-labs-add'),
    path('admin/section/<int:section_id>/labs/addother',
        admin_views.add_other_lab_in_section,
        name='admin-lab-section-labs-addother'),

    # announcement
    path('admin/section/<int:section_id>/announcements/',
        admin_views.list_announcements,
        name='admin-lab-section-announcements'),
    path('admin/section/<int:section_id>/announcements/add',
        admin_views.add_announcement,
        name='admin-lab-section-announcements-add'),
    path('admin/section/<int:section_id>/announcements/update',
        admin_views.update_announcements,
        name='admin-lab-section-announcements-update'),
]

templates/lab/base.html
{% extends "base.html" %}
{% load static %}
{% load elab_conf %}
{% load elab_request %}

{% block extra-head %}
{{block.super}}
<script type="text/javascript" src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/csrf.js' %}"></script>
<script type="text/javascript" src="{% static '/js/reverse.js' %}"></script>
<script type="text/javascript" src="{% static '/js/elab-client.js' %}"></script>
<link type="text/css" rel="stylesheet" href="{% static '/css/jquery-ui.min.css' %}" />
{% endblock %}

{% block headerbar_info %}
<div id="welcome">Welcome <b>{{ user.first_name }} {{ user.last_name }}</b>
{% if request %}[{% remote_addr request %}]{% endif %}</div>
{% endblock %}

{% block headerbarmenu %}
{% if user.is_staff %}
[<a href="{% url 'admin:index' %}">Admin</a>]
{% endif %}
[<a href="{% url 'logout' %}">Log out</a>]
{% endblock %}
    
{% block footer %}
<div id="footer" style="font-size: 70%; margin-top: 5px; padding-left: 5px; border-top: 1px lightgrey solid; color: grey;">
Icons from <a href="http://sweetie.sublink.ca/">Sweetie</a>.
</div>
{% endblock %}

templates/lab/error.html
{% extends "lab/base.html" %}

{% block title %}Error{% endblock %}

{% block content %}
<div style="padding:10px">
  <span style="color:red">{{message}}</span>
</div>
{% endblock %}

templates/lab/index.html
{% extends "lab/base.html" %}

{% block title %}Listing{% endblock %}

{% block content %}
<div id="first-page">
  {% if teaches %}
    {% if svn_revision %}
      <div style="float:right">
        (Revision: {{ svn_revision }})
      </div>
    {% endif %}
    <h1>Teach</h1>
    <ul class="section-list">
      {% for sec in teaches %}
        <li>
          <div class="section-link">
	    <a href="{% url 'instr:section-menu' sec.id %}">{{ sec }}</a>
	  </div>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

  <h1>Learn</h1>
  <ul class="section-list">
    {% for sec in learns %}
      <li>
        <div class="section-link">
  	  <a href="{% url 'lab:list-labs' sec.id %}">{{ sec }}</a>
	</div>
	{% if sec.published_announcements %}
          {% load markdown_filter %}
          {% for a in sec.published_announcements %}
            <div class="announcement">
      	      <div class="title">{{ a.title }}</div>
	      <div class="body">
		{{ a.body|markdown|safe }}
	      </div>
            </div>
          {% endfor %}
        {% endif %}
      </li>
    {% empty %}
      <i>You currently have no class to learn.</i>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/lab/labs.html
{% extends "lab/base.html" %}

{% load elab_submission %}

{% block title %}Listing{% endblock %}

{% block headerbarmenu %}
[<a href="{% url 'index' %}">Back to Courses</a>]
{{ block.super }}
{% endblock %}

{% block content %}
<h1>{{ sec.course }}</h1>
<table id="section-lab-list" width="100%">
  <tbody>
    <tr>
      <th width="5%"></th>
      <th width="50%">Labs</th>
      <th width="40%">Status</th>
    </tr>
    {% for labinsec,status in labs_with_statuses %}
      <tr>
        <td>{{ labinsec.number }}</td>
        <td>
          {% if labinsec.disabled %}
            <span style="color:#aaa">{{ labinsec.lab.name }}</span>
            <span class="label label-danger">disabled</span>
          {% elif labinsec.direct_to_lab_required %}
            <span style="color:#aaa">{{ labinsec.lab.name }}</span>
            <span class="label label-warning">direct account only</span>
          {% else %}
            <a href="{% url 'lab:show-lab' sec.id labinsec.id %}">{{ labinsec.lab.name }}</a>
            {% if labinsec.read_only %}
            <span class="label label-info">read-only</span>
            {% endif %}
          {% endif %}
        </td>
        <td>
          {% if status %}
            {% lab_status user sec status %}
            &nbsp;&nbsp;
            {% lab_manual_status status %}
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/lab/show.html
{% extends "lab/base.html" %}

{% load elab_submission %}
{% load elab_conf %}
{% load static %}
{% load mathjax %}

{% block extra-head %}
{{block.super}}
<link type="text/css" rel="stylesheet" href="{% static '/css/css-stars.css' %}" />
<script type="text/javascript" src="{% static '/js/jquery.barrating.min.js' %}"></script>
{% mathjax %}
<script type="text/javascript">
  lab_id = {{ lab.id }};

  function load_assignment(assignment_id) {
    $.get(Urls["lab:get-assignment"]({{sec.id}},{{labinsec.id}},assignment_id), 
          function(data) {
            $("#assignment").html(data);
            MathJax.Hub.Queue(["Typeset",MathJax.Hub,"assignment-body"]);
          });
  }

  function choose_assignment(assignment_id) {
    $("#nav-links div.task").removeClass("chosen");
    $("div#assignment-" + assignment_id).addClass("chosen");
  }

  function adjust_panels() {
    var sidebar_width;
    if ($("#nav-links").is(":visible"))
      sidebar_width = $("#nav-links").outerWidth();
    else
      sidebar_width = 0;
    var content_width = $(window).width() - sidebar_width;
    $("#nav-content").width(content_width);

    var toppanel_height = $("#header").height();
    $("#toggle-sidebar").css("top",toppanel_height);
  }

  $(document).ready(function() {
    // add code to each assignment link
    {% for assignment,submission in assignments %}
      $("#assignment-{{ assignment.id }}").click(function(event) {
        event.preventDefault();
        choose_assignment({{ assignment.id }});
        load_assignment({{ assignment.id }});
      });
    {% endfor %}

    $("#toggle-sidebar").on("click",function() {
      $("#nav-links").css("opacity",0);
      $("#nav-links").toggle("slide",function() {
        $("#nav-links").css("opacity",1);
        adjust_panels();
      });
    });

    adjust_panels();
    $(window).resize(adjust_panels);
  });
</script>
{% endblock extra-head %}

{% block title %}{{ sec.course.name }} | {{ lab.name }}{% endblock %}

{% block top_title %}
{{ block.super }}
| <a href="{% url 'lab:list-labs' sec.id %}">{{ sec.course.name }}</a>
{% endblock %}

{% block headerbarmenu %}
[<a href="{% url 'lab:list-labs' sec.id %}">All labs</a>]
{{ block.super }}
{% endblock %}

{% block content %}
<div id="container">
  <div id="nav-links">
  {% block contentnav %}
    <div id="lab-title" style="padding-bottom: 5px; padding-top: 10px;">
      <div>
        Lab {{labinsec.number}}:
      </div>
      <div>
        {{ lab.name }}
        {% if labinsec.read_only %}
          <span class="label label-warning">read-only</span>
        {% endif %}
      </div>
    </div>
    {% for assignment,submission in assignments %}
    <div class="task {% ifequal cur_assignment.id assignment.id %}chosen{% endifequal %}"
         id="assignment-{{ assignment.id }}">
      <span style="color:blue">{{ assignment.number }} - {{ assignment.task.name }}</span>
      <div id="assignment-status-icon-{{ assignment.id }}" style="display: inline">
        {% include "lab/include/submission_status_icon.html" %}
      </div>
    </div>
    {% endfor %}
  {% endblock contentnav %}
  </div>

  <div id="nav-content" style="display: table-cell">
    <label id="toggle-sidebar" title="Toggle side bar">&lt;|&gt;</label>
    <div id="assignment">
      {% if cur_assignment %}
        {% with assignment=cur_assignment submissions=cur_submissions %}
          {% include "lab/include/assignment.html" %}
        {% endwith %}
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}
{% block footer %}
{{ block.super }}
<script>
  all_manual_scores = {{all_manual_scores|safe}};
</script>
{% endblock %}