cms/urls.py
from django.urls import path
from . import admin_views
import search.admin_views as search_views
from .models import Lab, Task, Assignment, Course, LabInCourse
from .admin_views import AssignmentFormMock, LabInCourseFormMock

app_name = 'cms'

# Custom admin for cms: Task, Lab, Course
urlpatterns = [
    # for downloading solution code
    path('admin/task/<int:task_id>/solution/', admin_views.get_sol, 
        name='admin-cms-task-get-sol'),
    
    # this is an ajax request from admin/cms/task/change_form.html
    path('admin/task/preview/', admin_views.preview_task,
        name='admin-cms-task-preview'),

    # for previewing task on an iframe
    path('admin/task/preview-iframe/', admin_views.preview_task_as_iframe,
        name='admin-cms-task-preview-iframe'),

    # for previewing cached child task on an iframe
    path('admin/cachedchildtask/preview-iframe/<int:parent_task_id>/<key>', admin_views.preview_childtask_as_iframe,
        name='admin-cms-childtask-preview-iframe'),

    # for creating new task version
    path('admin/task/<int:task_id>/new_version/', admin_views.new_task_version,
        name='admin-cms-task-new-version'),

    # for cloning task
    path('admin/task/<int:task_id>/clone/', admin_views.clone_task,
        name='admin-cms-task-clone'),

    # for testing task
    path('admin/task/<int:task_id>/test/', admin_views.test_task,
        name='admin-cms-task-test'),

    path('admin/task/help/', admin_views.task_syntax_help,
        name='admin-cms-task-help'),

    path('admin/lab/<int:lab_id>/clone/', admin_views.clone_lab,
        name='admin-cms-lab-clone'),

    path('admin/lab/<int:lab_id>/deepclone/', admin_views.deepclone_lab,
        name='admin-cms-lab-deep-clone'),
]

# Common search admin
urlpatterns += [
    #
    # These are for task selection in lab
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/lab/search/', 
        search_views.search_children, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment,
            'search_result_template': 
                'admin/cms/lab/include/task_search_result.html',
            'search_function': Task.search_by_tags
            },
        'admin-cms-lab-task-search'),
    
    # this is ajax called from add button
    path('admin/lab/addtask/', 
        search_views.add_child, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment, 
            'join_form_mock': AssignmentFormMock,
            'one_join_form_template': 
                'admin/cms/lab/include/assignment_inline_oneform.html'
            },
        'admin-cms-lab-add-task'),


    #
    # These are for lab selection in course
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/course/search/', 
        search_views.search_children, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse,
            'search_result_template': 
                'admin/cms/course/include/lab_search_result.html',
            'search_function': Lab.search_by_tags
            },
        'admin-cms-course-lab-search'),
    
    # this is ajax called from add button
    path('admin/course/addlab/', 
        search_views.add_child, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse, 
            'join_form_mock': LabInCourseFormMock,
            'one_join_form_template': 
                'admin/cms/course/include/labincourse_inline_oneform.html' 
            },
        'admin-cms-course-add-lab'),
]

elabsheet/urls.py
import os
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from lab.views import index

urlpatterns = [
    path('', index,name='index'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('cms/', include('cms.urls')),
    path('lab/', include('lab.urls')),
    path('instr/', include('instr.urls')),
    path('feedback/', include('feedback.urls')),
    path('taskpads/', include('taskpads.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.MATHJAX_ROOT_URL, document_root=settings.MATHJAX_ROOT_DIR)

taskpads/urls.py
from django.urls import path
from . import views

app_name = 'taskpads'

urlpatterns = [
    path('',
        views.index,
        name='index'),
    path('new/',
        views.new,
        name='new'),


    path('preview/iframe/',
         views.preview_iframe,
         name='preview-iframe'),
    path('preview/',
         views.preview,
         name='preview'),

    path('test/<access_key>/<secret_key>/',
        views.test_task,
        name='test-task'),

    path('change/<access_key>/<secret_key>/',
        views.change,
        name='change'),
    path('manage/<access_key>/<secret_key>/',
        views.manage,
        name='manage'),
    path('newpost/<access_key>/<secret_key>/',
        views.create_post,
        name='newpost'),

    path('post/<post_key>/',
        views.edit_post,
        name='editpost'),

    path('show/<access_key>/',
        views.show,
        name='show'),
    path('clone/<access_key>/<share_key>/',
        views.clone,
        name='clone'),
    path('workon/<post_key>/<participant_key>/',
        views.workon,
        name='workon'),
    path('submit/<post_key>/<participant_key>/',
        views.ajax_submit,
        name='ajax_submit'),
    path('post/export/<post_key>.txt',
        views.post_export_txt,
        name='post_export_txt'),
    path('post/export/<post_key>.csv',
        views.post_export_csv,
        name='post_export_csv'),

    path('submission-status/<participant_key>/<int:submission_id>/',
        views.ajax_submission_status,
        name='ajax_submission_status'),
]

cms/models.py
import re
import os
import inspect
from django.db import models
from django.db.utils import IntegrityError
from django.template import Context,Template
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.exceptions import ValidationError
from django.dispatch import receiver

from .markdown_processor import process_markdown_source,insert_test_dialog
from .elab import Code
from sandbox import Sandbox,SourceCode
from .fields import CodeField
from commons.fields import LongJSONField
from commons.models import TestCaseResult

LANGS = ((x,x) for x in Sandbox.get_languages())

RE_REMOVE_WS = re.compile(r'\s')


class TagManager(models.Manager):
    """
    TagManager adds support for filter_by_tags to a model with tags.
    However, this method must be called directly from Model.objects,
    e.g., Model.objects.filter(xxx).filter_by_tags('hello') won't
    work.
    """

    # Tags routines
    @staticmethod
    def normalize_space(st):
        return ' '.join(st.strip().split())

    @staticmethod
    def normalize_tags(tags):
        """
        Returns a list of tags, space-normalized.
        """
        return [TagManager.normalize_space(x) for x in tags.split(',')]
   
    def filter_by_tags(self,tags):
        taglist = TagManager.normalize_tags(tags)
        candidates = self.model.objects.all()
        for tag in taglist:
            candidates = candidates.filter(tags__contains=tag)
        return candidates

class InvalidGenerator(Exception):
    pass

class InvalidTextGrader(Exception):
    pass

class Task(models.Model):
    """
    Task is a central model for E-Labsheet.

    It stores the basic unit of any labsheet: a task which consists of
    description, solution, code with fill-in form, and testdata (a set
    of testcases).
    
    It is also resposible for grading students' answers (mainly by
    executing the filled-in solution in a Sandbox and compare
    solutions).

    """
    name = models.CharField(max_length=100)
    note = models.CharField(max_length=100,
                            blank=True,
                            default='',
                            help_text='A one-line summary '
                            'of the task to be shown when '
                            'lab designer selects tasks.')
    source = models.TextField()
    language = models.CharField(max_length=20,choices=LANGS)
    lang_options = models.TextField(blank=True)
    html_template = models.TextField(blank=True)
    code = CodeField(blank=True)

    creator = models.ForeignKey(User,related_name='tasks_created',
                                blank=True,null=True,
                                on_delete=models.SET_NULL)
    owner = models.ForeignKey(User,related_name='tasks_owned',
                              blank=True,null=True,
                              on_delete=models.SET_NULL)

    disabled = models.BooleanField(blank=True,default=False)
    version = models.IntegerField(default=1)
    previous_version = models.ForeignKey('self',blank=True,
                                         null=True,default=None,
                                         on_delete=models.SET_NULL)

    is_private = models.BooleanField(default=False,
                help_text='If checked, this task becomes private to its creator '
                          'and owner')
    
    # simplest way to implement tags
    tags = models.CharField(max_length=200,
                            blank=True,
                            default='',
                            help_text='A comma-separated list '
                            'of tags. Each tag may contain spaces.')

    generator = models.TextField(
            blank=True,
            null=True,
            help_text=
                'Python script defining the function'
                ' <tt>generate(seed,difficulty)</tt> to generate a child task'
                ' by returning a dict of variable substituions.'
            )

    text_grader = models.TextField(
            blank=True,
            null=True,
            help_text=
                'Python script defining the function'
                ' <tt>grade(index,max_score,solution,answer)</tt> or'
                ' <tt>grade(index,max_score,solution,answer,elab)</tt>' 
                ' to return a score for the given answer,'
                ' or None if the answer is not to be graded.'
            )

    testcases = LongJSONField(blank=True, null=True)
    textblanks = LongJSONField(blank=True, null=True)

    objects = TagManager()

    def __str__(self):
        if (not self.disabled) or ('disabled' in self.name):
            return self.name
        else:
            return self.name + ' (disabled)'

    def enabled(self):
        return not self.disabled
    enabled.boolean = True   # This is needed for the admin page.
    
    ###########################
    # Various accessors
    #

    def solution(self):
        """
        Return the solution code from source.
        """
        return self.code.dump_solution()

    @staticmethod
    def build_blank_html_from_template(html_template):
        try:
            template = Template(html_template)
            context = Context({})
            return template.render(context)
        except Exception as e:
            #import traceback
            #traceback.print_exc()
            return "<p style='color:red'>Rendering error: {}<br/>{}</p>".format(
                    e.__class__.__name__,
                    e.template_debug["message"],
                    )

    @staticmethod
    def build_html_from_source(source,language):
        html,code,tests,textblanks = process_markdown_source(source,language)
        return Task.build_blank_html_from_template(html),textblanks

    def html(self):
        """
        Return a rendered html (with rendered forms) to be displayed.
        """
        return Task.build_blank_html_from_template(self.html_template)

    def has_manual_grading(self):
        return len(self.textblanks) != 0

    def manual_full_score(self):
        return sum([blank['score'] for blank in self.textblanks])

    ###########################
    # Methods for grading
    #

    @staticmethod
    def compare_result(result,expected):
        """
        Compare outputs from students' submission with the output from
        the provided solution.

        Currently all trailing whitespaces are removed before comparison.
        """
        if result is None:
            return TestCaseResult.FAILED
        result = '\n'.join([line.rstrip() for line in result.split('\n')])
        expected = '\n'.join([line.rstrip() for line in expected.split('\n')])
        if result.rstrip() == expected.rstrip():
            return TestCaseResult.PASSED
        if result.rstrip().lower() == expected.rstrip().lower():
            return TestCaseResult.CASEPROBLEM
        if RE_REMOVE_WS.sub('',result) == RE_REMOVE_WS.sub('',expected):
            return TestCaseResult.SPACEPROBLEM
        return TestCaseResult.FAILED


    def evaluate_built_source_with_messages(self,built_source,sandbox,
                                            input_data,
                                            capture=False):

        for supplement in self.supplement_set.all():
            supplement.unzip_to(sandbox.get_scratch_dir())

        output = sandbox.evaluate(built_source=built_source,
                                  input_string=input_data,
                                  capture=capture)

        messages = sandbox.get_compiler_messages()

        return output,messages


    def verify_with_messages(self,answer,output_list=None):
        submitted_code = self.code.dump(answer)
        src = SourceCode(self.language ,submitted_code)
        results = []
        messages = ''

        sandbox = Sandbox(settings.SANDBOX_SCRATCH_DIR,
                          temp_subdir=True,clean_dir=False,flags=self.code.flags)
        # extract supplements into scratch dir for compiling
        for supplement in self.supplement_set.all():
            supplement.unzip_to(sandbox.get_scratch_dir())
        built_source = sandbox.build(src)

        for testcase in self.testcases:
            output,messages = (
                self.evaluate_built_source_with_messages(
                    built_source,
                    sandbox,
                    testcase['input']+'\n')
                )

            this_result = {'task' : self,
                           'testcase' : testcase}
            this_result['passed'] = Task.compare_result(output,testcase['output'])
            results.append(this_result)
            if output_list!=None:
                output_list.append(output)

        sandbox.clean_scratch_dir()
        return results,messages


    def verify(self,answer,output_list=None):
        results,messages = self.verify_with_messages(answer,output_list)
        return results


    def verify_manual_auto_gradable_fields(self,answer):
        manual_scores = {}

        compiled_grader = self.compile_text_grader()
        # create dict for blank/answer pairs (answer key starts from zero)
        all_blanks = {}
        for b in self.textblanks:
            id = int(b['id'])
            if id-1 in answer:
                all_blanks[id] = (TextBlank(b,compiled_grader),answer[id-1])
            else:
                all_blanks[id] = (TextBlank(b,compiled_grader),None)
        for blank,ans in all_blanks.values():
            if not blank.auto_gradable:
                continue
            if ans is None:
                manual_scores[f'b{blank.id}'] = 0
                continue
            manual_scores[f'b{blank.id}'] = blank.grade_answer(ans,all_blanks)
        if manual_scores != {}:
            return manual_scores
        else:
            return None

    ###########################
    # Saving preparation methods
    #

    def run_testcase(self,built_source,sandbox,

taskpads/templates/taskpads/change.html
{% extends "taskpads/base.html" %}
{% load static %}

{% block title %}Taskpad Admin{% endblock %}

{% block extra-head %}
  <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">
{% endblock %}

{% block content %}
  <form method="post" action="">
    {% csrf_token %}
    <div class="container-fluid fullscreen-hide">
      <div class="row" style="margin-bottom: 8px;">
        <div class="col-sm-12">
          <div class="form-row">
            <div class="col-md-8">
              {{ form.name.errors }}
              {{ form.name }}
            </div>
            <div class="col-md-4">
              {% with 'edit' as current_page %}
                {% include "taskpads/include/header_menu.html" %}
              {% endwith %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div id="id_task_edit" class="col-sm-6">
          <div class="form-group fullscreen-hide">
            {{ form.language.errors }}
            <div class="row">
              <div class="col-sm-3 text-right">
                <label for="{{ form.language.id_for_label }}">ภาษาโปรแกรม</label>
              </div>
              <div class="col-sm-9">
                {{ form.language }}
              </div>
            </div>
          </div>
          <div class="form-group">
            <div style="float:right">
              <button id="id_button_maximize" class="btn btn-sm btn-outline-secondary fullscreen-hide" type="button">
                <i class="fa fa-expand-arrows-alt text-secondary"></i>
              </button>
              <button id="id_button_restore" class="btn btn-sm btn-outline-secondary fullscreen-show" style="display: none;" type="button">
                <i class="fa fa-compress text-secondary"></i>
              </button>
            </div>
            {{ form.source.errors }}
            {{ form.source }}
          </div>
          <div style="float:left">
            <button class="btn btn-primary" type="submit" name="action" value="save">จัดเก็บ</button>
          </div>
        </div>
        
        <div class="col-sm-6 fullscreen-hide">
          {% include "taskpads/include/task_preview.html" %}
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12" style="padding-top:5px">
          ลิงก์สำหรับแก้ไข (กรุณาจดบันทึก):
          <input
            id="taskpad-url"
            type="text"
            size="{{url|length}}"
            value="{{url}}"
            readonly
            style="color:grey"
          >
          <button class="btn btn-sm btn-light" type="button" id="btn-copy-url" title="Copy to clipboard"><i class="fa fa-copy" style="font-weight:100"></i></button>
        </div>
      </div>
      <hr>
      {% if task_pad.task.testcases %}
      <div class="row" id="accordion">
        <div class="col-sm-12" style="padding-top:5px">
          <h5 data-toggle="collapse" data-target="#testcases" style="cursor:pointer; color:blue">
            <i class="fa fa-caret-right"></i> รายการกรณีทดสอบ
          </h5>
        </div>
        <div class="col-sm-12 collapse" style="padding-top:5px" id="testcases">
          <table class="testcases">
            <tr class="head">
              <th style="width:1px; padding:5px;">ลำดับ</th>
              <th>อินพุท</th>
              <th>เอาท์พุท</th>
              <th>เปิดเผยอินพุท</th>
              <th>คำใบ้</th>
            </tr>
            {% for tc in task_pad.task.testcases %}
            <tr class="{% cycle 'odd' 'even' %}">
              <td>{{forloop.counter}}</td>
              <td class="input"><pre>{{tc.input}}</pre></td>
              <td class="output"><pre>{{tc.output}}</pre></td>
              <td>
                {% if tc.visible %}
                <i class="fa fa-check" style="color:green"></i>
                {% else %}
                <i class="fa fa-times" style="color:red"></i>
                {% endif %}
              </td>
              <td class="hint">
                {% if tc.hint %} {{tc.hint}} {% else %} - {% endif %}
              </td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      {% else %}
      <h5 style="color:red">ยังไม่มีกรณีทดสอบ</h5>
      {% endif %}
    </div>
  </form>

  {% include 'taskpads/include/syntax_help.html' %}
{% endblock %}
{% block content_script %}
  <script type="text/javascript" src="{% static '/js/jquery-fieldselection.js' %}"></script>
  <script type="text/javascript" src="{% static '/taskpads/js/taskpadeditor.js' %}"></script>
  <script>
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    var taskModified = false;

    var previewTask = function() {
      var language = $('#id_language').val();
      var src = $('#id_source').val();
      
      var url = '{% url 'taskpads:preview' %}';
      
      $('#refresh_notice_id').show();
      
      jQuery.post(url, {
        language: language,
        source: src,
        csrfmiddlewaretoken: csrftoken
      }, function(data) {
        var body = $('#preview_frame_id').contents().find('#assignment-body');
        body.html(data.html);
        $('#refresh_notice_id').fadeOut();
        document.getElementById("preview_frame_id").contentWindow.renderMathJax();
      });
    };

    var testTask = function() {
      var data = $('#preview_frame_id').contents().find('#preview_task_form_id').serialize();
      var url = '{% url 'taskpads:test-task' task_pad.access_key task_pad.secret_key  %}';

      $('#grading_notice_id').show();
      $('#grading_results_id').hide();
      jQuery.post(url,
                  data + "&csrfmiddlewaretoken=" + csrftoken,
                  function(data) {
                    $('#grading_notice_id').hide();
                    $('#grading_results_id').html('Graded: [' + data.results.join('') + ']');
                    $('#grading_results_id').show();
                  });
    };
    
    $(function(){
      previewTask();

      $('#task_preview_id').click(function() {
        previewTask();
        return false;
      });

      $('#test_task_link_id').click(function() {
        if(taskModified) {
          if(!confirm('มีการแก้ไขโจทย์ การทดสอบนี้จะทดสอบกับโจทย์ที่จัดเก็บล่าสุด ถ้าแน่ใจที่จะทดสอบให้กด Ok')) {
            return false;
          }
        }
        testTask();
        return false;
      });

      $('#id_source').change(function(){
        $('#test_task_link_id').removeClass('btn-success');
        $('#test_task_link_id').addClass('btn-secondary');
        taskModified = true;
      });

      $("#id_editor_button_help").click(function(){
        $('#syntax_help_frame_id').contents().find('h1').hide();
        $('#syntax_help_frame_id').contents().find('body').css('width','98%');
        $('#syntax_help_frame_id').contents().find('body').css('overflow-x','hidden');
        $('#syntax_help_frame_id').contents().find('#content').css('padding','0');
        $('#syntax_help_frame_id').contents().find('.form-row').css('width','98%');
        $('#syntax_help_modal_id').modal('show');
        return false;
      });

      $('#share_button_id').popover({
        trigger: 'focus',
        html: true,
        content: function() {
          return $('#share_popover_content_id').children('.popover-body').html();
        }
      });

      $('#id_button_maximize').click(function() {
        $(".fullscreen-hide").hide();
        $(".fullscreen-show").show();
        $("div#id_task_edit").removeClass('col-sm-6').addClass('col-sm-12');
        $("textarea#id_source").attr("rows","25");
      });
      $('#id_button_restore').click(function() {
        $(".fullscreen-hide").show();
        $(".fullscreen-show").hide();
        $("div#id_task_edit").removeClass('col-sm-12').addClass('col-sm-6');
        $("textarea#id_source").attr("rows","10");
      });

      $(".fullscreen-show").hide();

      $("#btn-copy-url").on("click",function() {
        $("#taskpad-url").select();
        document.execCommand('copy');
      });
    });
  </script>
{% endblock %}

taskpads/templates/taskpads/index.html
{% extends "taskpads/base.html" %}

{% block title %}Your Taskpad{% endblock %}

{% block content %}
  Your task pads:
  <ul>
    {% for task_pad in task_pads %}
      <li>
        {% if task_pad.task %}
          {{ task_pad.task }}
          [<a href="{% url 'taskpads:show' task_pad.access_key %}">View</a>]
        {% else %}
          empty task
        {% endif %}
        [<a href="{% url 'taskpads:change' task_pad.access_key task_pad.secret_key %}">Edit</a>]
      </li>
    {% empty %}
      <li>
        You have no task pads.
      </li>
    {% endfor %}
  </ul>

  Create <a href="{% url 'taskpads:new' %}">new task pad</a>.
{% endblock %}

taskpads/templates/taskpads/manage.html
{% extends "taskpads/base.html" %}

{% block title %}Taskpad Admin{% endblock %}
{% block extra-head %}
<style>
  table.explained-result {
    font-size: 80%;
    width: 100%;
    border-collapse: collapse;
  }
  table.explained-result th,
  table.explained-result tr,
  table.explained-result td {
    border: 1px solid grey;
    text-align: center;
  }
  table.explained-result td.input-data,
  table.explained-result td.hint {
    text-align: left;
  }
  table.explained-result tr.head {
    background-color: rgba(255,255,0,0.2);
  }

  table.explained-result tr.even {
    background-color: rgba(128,128,255,0.1);
  }

  table.explained-result td.na {
    background-color: #ccc;
  }
</style>
{% endblock %}

{% block content %}
  <div class="container-fluid">
    <div class="row" style="margin-bottom: 8px;">
      <div class="col-md-8">
        {% if task_pad.task %}
          <h3>{{ task_pad.task.name }}</h3>
        {% else %}
          <h3>ยังไม่ระบุชื่อโจทย์</h3>
        {% endif %}
      </div>
      <div class="col-md-4">
        {% with 'manage' as current_page %}
          {% include "taskpads/include/header_menu.html" %}
        {% endwith %}
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3" style="position: sticky; height: calc(100vh - 15rem);">
        <div id="post_list_group_id" class="list-group">
          {% for task_post in task_posts %}
            <a href="#post-item-{{ forloop.counter }}" class="list-group-item list-group-item-action {% if task_post.is_active %}active{% endif %}" data-toggle="list">กลุ่มผู้เรียนที่ {{ forloop.counter }}</a>
          {% endfor %}
        </div>
        
        <form method="post" action="{% url 'taskpads:newpost' task_pad.access_key task_pad.secret_key %}" class="mt-2">
          {% csrf_token %}
          <button class="btn btn-success btn-block">สร้างกลุ่มผู้เรียนใหม่</button>
        </form>
      </div>
      <div class="col-sm-9">
        <div class="tab-content">
          {% for task_post in task_posts %}
            <div class="tab-pane {% if task_post.is_active %}show active{% endif %}" id="post-item-{{ forloop.counter }}">
              <div style="float: left;">
                <h4 style="display: inline-block;">กลุ่มผู้เรียนที่ {{ forloop.counter }}</h4>
                สร้างเมื่อ {{ task_post.created_at|date:'Y-m-d' }} {{ task_post.created_at|time:'H:i:s' }}
                <a href="{% url 'taskpads:editpost' task_post.key %}" class="btn btn-sm btn-primary">แก้ไข</a>
                <a href="{% url 'taskpads:post_export_csv' task_post.key %}" class="btn btn-sm btn-info">.csv</a>
                <a href="{% url 'taskpads:post_export_txt' task_post.key %}" class="btn btn-sm btn-info" target="_blank">.txt</a>
              </div>
              <div style="clear: both;"></div>

              {% if task_post.is_active %}
                {% if messages %}
                  <ul class="messagelist">
                    {% for message in messages %}
                      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                  </ul>
                {% endif %}
              {% endif %}
              
              {% include "taskpads/include/task_post_in_manage.html" %}
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block content_script %}
  <script>
    $(function() {
      $('#share_button_id').popover({
        trigger: 'focus',
        html: true,
        content: function() {
          return $('#share_popover_content_id').children('.popover-body').html();
        }
      });

      var hash = window.location.hash;
      if (hash) {
        $('a.list-group-item[href="' + hash + '"]').tab('show');
      }

      $("a.list-group-item").on("click",function() {
        window.location.hash = $(this).attr("href");
      });
    });
  </script>
{% endblock %}

taskpads/templates/taskpads/preview_iframe.html
{% extends "taskpads/base_nohead.html" %}

{% load static %}
{% load elab_conf %}
{% load mathjax %}

{% block extra-head %}
  <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}" />
  {% mathjax %}
{% endblock extra-head %}

{% block content %}
  <form id="preview_task_form_id">
    <div id="assignment-body" style="padding: 3px;">
      Show me the task, with rendered math
      \[ x^2 + y \]
    </div>
  </form>
{% endblock %}

{% block content_script %}
  <script>
    function renderMathJax() {
      MathJax.Hub.Queue(["Typeset",MathJax.Hub,"assignment-body"]);
    }
    renderMathJax();
  </script>
{% endblock %}

taskpads/templates/taskpads/show.html
{% extends "taskpads/base.html" %}
{% load static %}
{% block extra-head %}
  <link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}" />
  <style>
   body {
       padding-top: 5rem;
   }
  </style>
{% endblock %}

{% block title %}Taskpad{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% if task %}
          {% include "taskpads/include/task.html" %}
        {% else %}
          Error: empty task
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}