cms/urls.py
from django.urls import path
from . import admin_views
import search.admin_views as search_views
from .models import Lab, Task, Assignment, Course, LabInCourse
from .admin_views import AssignmentFormMock, LabInCourseFormMock

app_name = 'cms'

# Custom admin for cms: Task, Lab, Course
urlpatterns = [
    # for downloading solution code
    path('admin/task/<int:task_id>/solution/', admin_views.get_sol, 
        name='admin-cms-task-get-sol'),
    
    # this is an ajax request from admin/cms/task/change_form.html
    path('admin/task/preview/', admin_views.preview_task,
        name='admin-cms-task-preview'),

    # for previewing task on an iframe
    path('admin/task/preview-iframe/', admin_views.preview_task_as_iframe,
        name='admin-cms-task-preview-iframe'),

    # for previewing cached child task on an iframe
    path('admin/cachedchildtask/preview-iframe/<int:parent_task_id>/<key>', admin_views.preview_childtask_as_iframe,
        name='admin-cms-childtask-preview-iframe'),

    # for creating new task version
    path('admin/task/<int:task_id>/new_version/', admin_views.new_task_version,
        name='admin-cms-task-new-version'),

    # for cloning task
    path('admin/task/<int:task_id>/clone/', admin_views.clone_task,
        name='admin-cms-task-clone'),

    # for testing task
    path('admin/task/<int:task_id>/test/', admin_views.test_task,
        name='admin-cms-task-test'),

    path('admin/task/help/', admin_views.task_syntax_help,
        name='admin-cms-task-help'),

    path('admin/lab/<int:lab_id>/clone/', admin_views.clone_lab,
        name='admin-cms-lab-clone'),

    path('admin/lab/<int:lab_id>/deepclone/', admin_views.deepclone_lab,
        name='admin-cms-lab-deep-clone'),
]

# Common search admin
urlpatterns += [
    #
    # These are for task selection in lab
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/lab/search/', 
        search_views.search_children, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment,
            'search_result_template': 
                'admin/cms/lab/include/task_search_result.html',
            'search_function': Task.search_by_tags
            },
        'admin-cms-lab-task-search'),
    
    # this is ajax called from add button
    path('admin/lab/addtask/', 
        search_views.add_child, {
            'parent_model': Lab, 
            'child_model': Task,
            'join_model': Assignment, 
            'join_form_mock': AssignmentFormMock,
            'one_join_form_template': 
                'admin/cms/lab/include/assignment_inline_oneform.html'
            },
        'admin-cms-lab-add-task'),


    #
    # These are for lab selection in course
    #

    # this is ajax called from search button (from admin/lab/assignment-block)
    path('admin/course/search/', 
        search_views.search_children, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse,
            'search_result_template': 
                'admin/cms/course/include/lab_search_result.html',
            'search_function': Lab.search_by_tags
            },
        'admin-cms-course-lab-search'),
    
    # this is ajax called from add button
    path('admin/course/addlab/', 
        search_views.add_child, {
            'parent_model': Course, 
            'child_model': Lab,
            'join_model': LabInCourse, 
            'join_form_mock': LabInCourseFormMock,
            'one_join_form_template': 
                'admin/cms/course/include/labincourse_inline_oneform.html' 
            },
        'admin-cms-course-add-lab'),
]

elabsheet/urls.py
import os
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from lab.views import index

urlpatterns = [
    path('', index,name='index'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('cms/', include('cms.urls')),
    path('lab/', include('lab.urls')),
    path('instr/', include('instr.urls')),
    path('feedback/', include('feedback.urls')),
    path('taskpads/', include('taskpads.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.MATHJAX_ROOT_URL, document_root=settings.MATHJAX_ROOT_DIR)

taskpads/urls.py
from django.urls import path
from . import views

app_name = 'taskpads'

urlpatterns = [
    path('',
        views.index,
        name='index'),
    path('new/',
        views.new,
        name='new'),


    path('preview/iframe/',
         views.preview_iframe,
         name='preview-iframe'),
    path('preview/',
         views.preview,
         name='preview'),

    path('test/<access_key>/<secret_key>/',
        views.test_task,
        name='test-task'),

    path('change/<access_key>/<secret_key>/',
        views.change,
        name='change'),
    path('manage/<access_key>/<secret_key>/',
        views.manage,
        name='manage'),
    path('newpost/<access_key>/<secret_key>/',
        views.create_post,
        name='newpost'),

    path('post/<post_key>/',
        views.edit_post,
        name='editpost'),

    path('show/<access_key>/',
        views.show,
        name='show'),
    path('clone/<access_key>/<share_key>/',
        views.clone,
        name='clone'),
    path('workon/<post_key>/<participant_key>/',
        views.workon,
        name='workon'),
    path('submit/<post_key>/<participant_key>/',
        views.ajax_submit,
        name='ajax_submit'),
    path('post/export/<post_key>.txt',
        views.post_export_txt,
        name='post_export_txt'),
    path('post/export/<post_key>.csv',
        views.post_export_csv,
        name='post_export_csv'),

    path('submission-status/<participant_key>/<int:submission_id>/',
        views.ajax_submission_status,
        name='ajax_submission_status'),
]

taskpads/views.py
import json
from datetime import datetime
import csv
import codecs

from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.urls import reverse

from django.forms import ModelForm, Textarea, TextInput, Select
from django.utils import timezone
from django.contrib import messages
from django.conf import settings
from django.template.loader import render_to_string

from django.contrib.auth.models import User

from .models import TaskPad, TaskPost, Participant
from .utils import make_result_explanation
from cms.models import Task, Assignment
from lab.models import Submission
from lab.views import build_answer
from logger.models import Log
from commons.decorators import taskpads_required
from commons.utils import get_remote_addr_from_request

def create_new_task_pad_and_redirect(creator=None):
    task_pad = TaskPad.create_for(creator)
    if task_pad:
        return redirect(reverse('taskpads:change', args=[task_pad.access_key,
                                                         task_pad.secret_key]))
    else:
        raise Exception('Task pad saving error')

    
@taskpads_required
def create_new_task_post_and_redirect(request,task_pad):
    if request.user.is_authenticated:
        creator = request.user
    else:
        creator = None
    post = TaskPost.create_for(task_pad, creator)
    return redirect(reverse('taskpads:editpost', args=[post.key]))


@taskpads_required
def index(request):
    if not request.user.is_authenticated:
        return create_new_task_pad_and_redirect()
    task_pads = TaskPad.objects.filter(creator=request.user).all()
    return render(request,
                  'taskpads/index.html',
                  { 'task_pads': task_pads })


@taskpads_required
def new(request):
    if not request.user.is_authenticated:
        return create_new_task_pad_and_redirect()
    else:
        return create_new_task_pad_and_redirect(request.user)

    
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name',
                  'language',
                  'source']
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'ชื่อโจทย์',
            }),
            'language': Select(attrs={'class': 'form-control'}),
            'source': Textarea(attrs={'class': 'form-control'}),
        }

        
@taskpads_required
def change(request, access_key, secret_key):
    task_pad = get_object_or_404(TaskPad,
                                 access_key=access_key)
    if task_pad.secret_key != secret_key:
        raise PermissionDenied

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task_pad.task)
        if form.is_valid():
            task = form.save()
            task_pad.task = task
            task_pad.updated_at = timezone.now()
            task_pad.save()
    else:
        form = TaskForm(instance=task_pad.task)

    url = request.build_absolute_uri(reverse('taskpads:change',args=[
        task_pad.access_key,
        task_pad.secret_key ]))

    return render(request,
                  'taskpads/change.html',
                  { 'task_pad': task_pad,
                    'form': form,
                    'url': url})


@taskpads_required
def manage(request, access_key, secret_key):
    task_pad = get_object_or_404(TaskPad,
                                 access_key=access_key)
    if task_pad.secret_key != secret_key:
        raise PermissionDenied

    task_posts = task_pad.task_posts.all()

    active_post_key = request.GET.get('key','')
    post_form_visible = request.GET.get('post_form','') == 'true'

    if active_post_key == '':
        if len(task_posts)!=0:
            task_posts[0].is_active = True
    else:
        for task_post in task_posts:
            if task_post.key == active_post_key:
                task_post.is_active = True
    
    return render(request,
                  'taskpads/manage.html',
                  { 'task_pad': task_pad,
                    'task_posts': task_posts,
                    'active_post_key': active_post_key,
                    'post_form_visible': post_form_visible })


@taskpads_required
def create_post(request, access_key, secret_key):
    task_pad = get_object_or_404(TaskPad,
                                 access_key=access_key)
    if task_pad.secret_key != secret_key:
        raise PermissionDenied

    if request.method == 'POST':
        return create_new_task_post_and_redirect(request,task_pad)
    else:
        raise PermissionDenied

    
@taskpads_required
def preview(request):
    if request.method == 'POST':
        source = request.POST.get('source')
        lang   = request.POST.get('language')
    else:
        source = request.GET.get('source')
        lang   = request.GET.get('language')
    html, textblanks = Task.build_html_from_source(source, lang)
    sols = [("b%d" % i,s,p) for (i,(s,p)) in textblanks.items()]

    return HttpResponse(json.dumps({
        "html" : html,
        "sols" : sols,
    }), content_type="application/json")

@taskpads_required
def preview_iframe(request):
    return render(request,
                  'taskpads/preview_iframe.html')

@taskpads_required
def test_task(request, access_key, secret_key):
    task_pad = get_object_or_404(TaskPad,
                                 access_key=access_key)
    if task_pad.secret_key != secret_key:
        raise PermissionDenied

    if request.method!='POST':
        raise PermissionDenied
        
    task = task_pad.task
    if not task:
        raise PermissionDenied

    from lab.views import build_answer
    from lab.models import Submission

    answer = build_answer(request.POST.items(),
                          request.FILES.items())
    
    grading_results = task.verify(answer)
    result_list = [r['passed'] for r in grading_results]
    manual_grading_results = task.verify_manual_auto_gradable_fields(answer)
    submission = Submission(assignment=Assignment(lab=None,task=task),
                            answer=answer,
                            results=result_list,
                            manual_scores=manual_grading_results,
                            submitted_at=datetime.now())
    testcases = task.testcases
    results = zip(testcases,submission.results)
    
    submission.prerendered_results = render_to_string(
        'lab/include/explained_results.html',
        { 'submission' : submission, 'results' : results })

    res_data = {
        'results': [str(r) for r in submission.results],
        'detailed': submission.prerendered_results,
    }
    return HttpResponse(json.dumps(res_data),
                        content_type="application/json")


class TaskPostForm(ModelForm):
    class Meta:
        model = TaskPost
        fields = ['participants','enabled']
        widgets = {
            'participants': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '# ป้อนชื่อผู้เรียนบรรทัดละหนึ่งชื่อ\n'
                               '# ระบบจะไม่สนใจบรรทัดว่างหรือบรรทัดที่ขึ้นต้นด้วย #',
                }),
        }
    
@taskpads_required
def edit_post(request, post_key):
    post = get_object_or_404(TaskPost, key=post_key)

    if request.method == 'POST':
        form = TaskPostForm(request.POST, instance=post)
        if form.is_valid():
            messages.success(request, "Task post saved successfully")
            post = form.save()
            return redirect(reverse('taskpads:manage',
                                    args=[post.task_pad.access_key,
                                          post.task_pad.secret_key]) +
                            '?key=' + post.key)
    else:
        form = TaskPostForm(instance=post)

    return render(request, 'taskpads/task_post.html', {
        'post': post,
        'form': form,
    })

@taskpads_required
def render_task_pad_for_submission(request,
                                   post,
                                   task_pad,
                                   task,
                                   participant,
                                   recent_submission,
                                   is_anonymous=False,
                                   share_key=None):
    return render(request, 'taskpads/workon.html', {
        'post' : post,
        'task_pad': task_pad,
        'task': task,
        'participant': participant,
        'recent_submission': recent_submission,
        'is_anonymous': is_anonymous,
        'share_key': share_key,
    })


@taskpads_required
def clone(request, access_key, share_key):
    task_pad = get_object_or_404(TaskPad,
                                 access_key=access_key)

    share_key = request.GET.get('sharing',None)

    if share_key and share_key != task_pad.get_share_key():
        return HttpResponse(status=403)

    if request.method == 'POST':
        if request.user.is_authenticated:
            creator = request.user
        else:
            creator = None
        new_task_pad = TaskPad.clone(task_pad,
                                     creator,
                                     'taskpad task clone from pad: %d' % (task_pad.id,))
        return HttpResponse(json.dumps({ 'access_key': new_task_pad.access_key,
                                         'secret_key': new_task_pad.secret_key, }),
                            content_type="application/json")
    else:
        return HttpResponse(status=403)

    
@taskpads_required
def show(request, access_key):
    task_pad = get_object_or_404(TaskPad,
                                 access_key=access_key)

    share_key = request.GET.get('sharing',None)

    if share_key and share_key != task_pad.get_share_key():
        return HttpResponse(status=403)

    task = task_pad.task
    post = TaskPost(key=task_pad.access_key)

taskpads/templates/taskpads/include/header_menu.html
<div class="btn-group">
  <a href="{% url 'taskpads:change' task_pad.access_key task_pad.secret_key %}" class="btn {% if current_page == 'edit' %}btn-primary{% else %}btn-outline-secondary{% endif %}">แก้ไขโจทย์</button>
  <a href="{% url 'taskpads:manage' task_pad.access_key task_pad.secret_key %}" class="btn {% if current_page == 'manage' %}btn-primary{% else %}btn-outline-secondary{% endif %}">จัดการ</a>
  <button id="share_button_id" type="button" class="btn btn-outline-secondary" data-toggle="popover" data-placement="bottom" title="แบ่งปันโจทย์นี้">แชร์</button>
</div>

{% include 'taskpads/include/share_popover_content.html' %}

taskpads/templates/taskpads/include/share_popover_content.html
<div id="share_popover_content_id" class="d-none">
  <div class="popover-body">
    สามารถแบ่งปันโจทย์ได้สองรูปแบบ<br />
    <span class="badge badge-primary">1</span> แบ่งปันโจทย์:<br />
    <pre class="p-1 bg-light"><a href="{% url 'taskpads:show' task_pad.access_key %}" target="_blank">{{ task_pad.access_key }}</i></a> <a href="{% url 'taskpads:show' task_pad.access_key %}" target="_blank"><i class="fa fa-link"></i></a></pre>
    <span class="badge badge-primary">2</span> แบ่งปันโจทย์ที่คัดลอกไปใช้ต่อได้ (พร้อมเฉลย):
    <pre class="p-1 bg-light"><a href="{% url 'taskpads:show' task_pad.access_key %}?sharing={{ task_pad.get_share_key }}" target="_blank">{{ task_pad.access_key }}/?sharing={{ task_pad.get_share_key }}</a> <a href="{% url 'taskpads:show' task_pad.access_key %}?sharing={{ task_pad.get_share_key }}" target="_blank"><i class="fa fa-link"></i></a></pre>
    <span class="badge badge-danger">ระวัง</span> อย่าให้ลิงก์แบบที่สองกับนักเรียน
  </div>
</div>

taskpads/templates/taskpads/include/syntax_help.html
<div id="syntax_help_modal_id" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Editor syntax help</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe
          id="syntax_help_frame_id"
          style="border: 0px solid lightgray; margin-top: 5px; width: 100%; height: 300px; overflow: hidden scroll;"
          src="{% url 'cms:admin-cms-task-help' %}">
        </iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

taskpads/templates/taskpads/include/task.html
<h1>{{ task.name }}</h1>
<div style="padding: 5px; border: 1px solid lightgray; border-radius: 5px;">
  {{ task.html }}
</div>

taskpads/templates/taskpads/include/task_post_in_manage.html
<b>รายชื่อและสถานะผู้เรียน</b>
{% include 'taskpads/include/task_post_participant_table.html' %}

taskpads/templates/taskpads/include/task_post_participant_table.html
<table class="table table-striped table-sm">
  <thead class="thead-dark">
    <tr>
      <th class="text-center">ลำดับ</th>
      <th>ชื่อ</th>
      <th>ลิงก์</th>
      <th class="text-center">ส่งล่าสุด</th>
      <th class="text-center">ผล</th>
      <th class="text-center">รายละเอียด</th>
    </tr>
  </thead>
  <tbody>
    {% for participant in task_post.participant_set.all %}
    {% with status=participant.latest_submission_status %}
      <tr>
        <td class="text-center">{{participant.order}}</td>
        <td>{{participant.name}}</td>
        <td>
          <a href="{% url 'taskpads:workon' task_post.key participant.key %}" target="_blank">
            <i class="fa fa-link"></i>
          </a>
        </td>
        {% if status %}
          <td class="text-center">
            {{status.submitted_at}}
          </td>
          <td class="text-center">
            {% if status.graded %}
              {% if status.passed %}
              <i class="fa fa-check" id="status-passed" style="color:green"></i>
              {% else %}
              <i class="fa fa-times" id="status-failed" style="color:red"></i>
              {% endif %}
            {% else %}
              <i class="fa fa-clock" id="status-grading" style="color:blue; font-weight:100"></i>
            {% endif %}
          </td>
          <td class="text-center">
            [<span style="font-family:monospace">{{status.results}}</span>]
            <!-- detailed results dialog -->
            <div class="modal" id="detail-{{participant.key}}" tabindex="-1" role="dialog">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">อธิบายผลลัพธ์</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {{status.result_explanation}}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">ปิด</button>
                  </div>
                </div>
              </div>
            </div>
            <button class="borderless" style="color:green" data-toggle="modal" data-target="#detail-{{participant.key}}">
              <i class="fa fa-clipboard" style="font-weight:100"></i>
            </button>
            {% if status.compiler_messages %}
              <!-- compiler messages dialog -->
              <div class="modal" id="compiler-{{participant.key}}" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">รายงานความผิดพลาดจากคอมไพเลอร์</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body" style="text-align:left">
                      <pre id="pre-compiler-messages">{{status.compiler_messages}}</pre>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-dismiss="modal">ปิด</button>
                    </div>
                  </div>
                </div>
              </div>
              <button class="borderless" style="color:orange" data-toggle="modal" data-target="#compiler-{{participant.key}}">
                <i class="fa fa-bolt"></i>
              </button>
            {% endif %}
          </td>
        {% else %}
          <td class="text-center">-</td>
          <td class="text-center">-</td>
          <td class="text-center">-</td>
        {% endif %}
      </tr>
    {% endwith %}
    {% endfor %}
  </tbody>
</table>

taskpads/templates/taskpads/include/task_preview.html
ตัวอย่าง <a href="#" id="task_preview_id" class="btn btn-sm btn-success"><i class="fas fa-sync-alt"></i></a>
<span style="display:none;" id="refresh_notice_id">Refreshing...</span>
<span style="display:none;" id="grading_notice_id">Grading...</span>
<span style="display:none;" id="grading_results_id"></span>
<div>
  <iframe
    id="preview_frame_id"
    style="border: 1px solid lightgray; border-radius: 5px; width: 100%; height: 300px;"
    class="mt-1"
    src="{% url 'taskpads:preview-iframe' %}">
  </iframe>
</div>
{% if task_pad.task %}
  <a id="test_task_link_id" href="#" class="btn btn-success">ทดสอบส่ง</a>
{% endif %}
<small><span class="text-muted">กรุณาจัดเก็บก่อน เพื่อทดสอบกับการแก้ไขล่าสุด</span></small>